# Generated by Django 3.2.9 on 2021-11-05 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short', '0002_alter_link_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shortlink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortlink', models.URLField(max_length=10000)),
            ],
            options={
                'verbose_name': 'Короткая ссылка',
                'verbose_name_plural': 'Короткие ссылки',
            },
        ),
    ]
