# Generated by Django 3.2.9 on 2021-11-05 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short', '0003_shortlink'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shortlink',
        ),
        migrations.AddField(
            model_name='link',
            name='shortlink',
            field=models.URLField(default=123, max_length=100),
            preserve_default=False,
        ),
    ]
