# Generated by Django 3.2.9 on 2021-11-07 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short', '0004_auto_20211105_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='link',
            field=models.URLField(max_length=1000),
        ),
    ]
