# Generated by Django 3.2.9 on 2021-11-10 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short', '0008_alter_link_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
