# Generated by Django 3.2.9 on 2021-11-10 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short', '0010_alter_link_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
