# Generated by Django 3.2.9 on 2022-07-11 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('short', '0012_alter_link_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ['-id_link'], 'verbose_name': 'Ссылка', 'verbose_name_plural': 'Ссылки'},
        ),
        migrations.RenameField(
            model_name='link',
            old_name='id',
            new_name='id_link',
        ),
    ]
